version: 2
jobs:
  build:
    working_directory: ~/EmpiresCommunity/website
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: ubuntu:18.04
    steps:
    - checkout
    - run: apt-get update
    - run: apt-get --yes install cabal-install haskell-stack libz-dev netbase locales
    - run:
        working_directory: ~/EmpiresCommunity/website
        command: echo -e "export PATH=/opt/ghc/7.8.4/bin:$PATH" >> $BASH_ENV
    - run: cabal update
    #- run: cabal install --dependencies-only --avoid-reinstalls --reorder-goals
    - run: stack setup
    - run: locale-gen
    #- run: cabal build
    #- run: cabal test --show-details=always
    - run: LANG=en_US.UTF-8 make
    - run: LANG=en_US.UTF-8 make deploy
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
